import React from "react";
import { X, ArrowLeft, CheckCircle2 } from "lucide-react";
import tcRaw from "./tc.txt?raw";

export type LegalDocType = "terms" | "risk" | "offtake" | "privacy" | "aml";

interface Section {
  id: string;
  title: string;
  content: React.ReactNode;
}

const parseTcText = (text: string): Section[] => {
  const sections = text.trim().split(/\n\n(?=\d+\. )/);
  return sections.map((sectionText) => {
    const lines = sectionText.split("\n");
    const title = lines[0];
    const id = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    const content = (
      <div className="space-y-3">
        {lines.slice(1).map((p, i) => (
          <p key={i}>{p}</p>
        ))}
      </div>
    );
    return { id, title, content };
  });
};

const RISK_DISCLOSURE_SECTIONS: Section[] = [
  {
    id: "risk-intro",
    title: "1. Agricultural & Biological Realities",
    content: (
      <div className="space-y-3">
        <p>
          Investments in apiculture (beekeeping) involve physical, biological assets that operate subject to seasonal climate, flora bloom cycles, and local ecological conditions across Ghanaian regional apiaries.
        </p>
        <p>
          While One Hive Africa enforces precision apiary management, investors acknowledge that honey yields fluctuate based on ambient rainfall patterns, temperature, and flowering nectar flow in regions such as Hohoe, Ejura, and Aburi.
        </p>
      </div>
    ),
  },
  {
    id: "risk-absconding",
    title: "2. Colony Absconding & Disease Safeguards",
    content: (
      <div className="space-y-3">
        <p>
          African honeybees (Apis mellifera adansonii) exhibit natural migratory instincts and may occasionally abscond due to excessive dry seasons, pests, or predator activity.
        </p>
        <p>
          <strong>One Hive Mitigation Policy:</strong> To protect investor capital, One Hive Africa operates a colony buffer reserve. If an invested hive absconds, our beekeepers perform baiting, queen introduction, or re-siting at no additional operational cost to the investor.
        </p>
      </div>
    ),
  },
  {
    id: "risk-returns",
    title: "3. Non-Guaranteed Return Estimates",
    content: (
      <div className="space-y-3">
        <p>
          Projected Annual Percentage Returns (20% – 26% APR) reflect verified historical performance and wholesale commodity honey benchmarks. They do not constitute guaranteed fixed-income bank yields.
        </p>
        <p>
          Actual distributions are calculated strictly from harvested, cold-filtered Grade-A honey sold through One Hive Africa's verified commercial distribution channels.
        </p>
      </div>
    ),
  },
  {
    id: "risk-liquidity",
    title: "4. Capital Commitment & Harvest Cycles",
    content: (
      <div className="space-y-3">
        <p>
          Capital deployed into beehives is physically allocated to timber hive construction, protective gear, swarm capture, and apiary siting. Funds cannot be liquidated midway through an active 12-month or multi-year production cycle.
        </p>
        <p>
          Capital redemptions occur upon cycle maturity following the final seasonal honey extraction and accounts reconciliation.
        </p>
      </div>
    ),
  },
];

const OFFTAKE_SECTIONS: Section[] = [
  {
    id: "offtake-guarantee",
    title: "1. 100% Guaranteed Off-Take Commitment",
    content: (
      <div className="space-y-3">
        <p>
          One Hive Africa legally enters into a 100% commercial off-take purchase agreement for all honey and bee by-products (beeswax, propolis) generated by investor-sponsored hives.
        </p>
        <p>
          Investors are never required to independently package, transport, market, or locate retail buyers for honey harvested from their hives.
        </p>
      </div>
    ),
  },
  {
    id: "offtake-pricing",
    title: "2. Benchmark Wholesale Pricing Formula",
    content: (
      <div className="space-y-3">
        <p>
          Raw comb and strained honey are purchased at established wholesale benchmark prices pegged against premium commercial culinary and export grades.
        </p>
        <p>
          Harvest logs, weight certificates, and moisture refractometer readouts (&lt;19% moisture content) are uploaded to the investor dashboard prior to payout calculation.
        </p>
      </div>
    ),
  },
  {
    id: "offtake-payouts",
    title: "3. Bi-Annual Harvest Settlement SLA",
    content: (
      <div className="space-y-3">
        <p>
          Honey is harvested in two principal Ghanaian flows: Minor Season (May – July) and Major Season (November – January).
        </p>
        <p>
          Proceeds from honey sales are deposited directly to your verified Mobile Money (MTN, Telecel, AT) or Ghanaian bank account within 30 days of batch lab clearance and wholesale delivery.
        </p>
      </div>
    ),
  },
];

const PRIVACY_SECTIONS: Section[] = [
  {
    id: "privacy-compliance",
    title: "1. Compliance with Ghana Data Protection Act, 2012 (Act 843)",
    content: (
      <div className="space-y-3">
        <p>
          One Hive Africa operates in strict adherence to Act 843 of the Parliament of Ghana. All investor personal, telephone, and financial account identifiers are stored under bank-grade encryption protocols.
        </p>
      </div>
    ),
  },
  {
    id: "privacy-usage",
    title: "2. KYC & Payout Data Retention",
    content: (
      <div className="space-y-3">
        <p>
          Your identification records (Ghana Card / Passport) are utilized solely for statutory Know-Your-Customer (KYC) compliance and fraud prevention. We never monetize, sell, or disclose investor records to third-party marketing entities.
        </p>
      </div>
    ),
  },
];

interface DocumentMeta {
  title: string;
  subtitle: string;
  sections: Section[];
}

const getDocumentMeta = (docType: LegalDocType): DocumentMeta => {
  switch (docType) {
    case "risk":
      return {
        title: "Agricultural Risk & Biological Factor Disclosures",
        subtitle: "Official apiculture disclosure regarding seasonal rainfall, nectar flow, and absconding safeguards",
        sections: RISK_DISCLOSURE_SECTIONS,
      };
    case "offtake":
      return {
        title: "100% Commercial Honey Off-Take Agreement",
        subtitle: "Legally binding commitment by One Hive Africa to purchase all harvested honey at wholesale benchmark floors",
        sections: OFFTAKE_SECTIONS,
      };
    case "privacy":
      return {
        title: "Privacy Policy & KYC Protection (Act 843)",
        subtitle: "Ghana Data Protection Act (Act 843) compliance framework covering investor national identification and financial security",
        sections: PRIVACY_SECTIONS,
      };
    case "aml":
    case "terms":
    default:
      return {
        title: "Investor Terms of Service & Apiary Charter",
        subtitle: "Governed under the Commercial and Agricultural Laws of the Republic of Ghana",
        sections: [
          ...parseTcText(tcRaw),
          {
            id: "acceptance-of-terms",
            title: "11. Binding Charter Status",
            content: (
              <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-stone-800 space-y-2">
                <div className="flex items-center gap-2 text-emerald-800 font-bold text-sm">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                  Legally Signed & Active
                </div>
                <p className="text-xs leading-relaxed text-stone-600">
                  As an active registered investor on One Hive Africa, you have confirmed and executed this agreement upon platform enrollment and deployment of investment capital.
                </p>
              </div>
            ),
          },
        ],
      };
  }
};

interface TermsAndConditionsModalProps {
  onClose: () => void;
  docType?: LegalDocType;
  initialDoc?: LegalDocType;
}

const TermsAndConditionsModal: React.FC<TermsAndConditionsModalProps> = ({
  onClose,
  docType,
  initialDoc,
}) => {
  const selectedType = docType || initialDoc || "terms";
  const docMeta = getDocumentMeta(selectedType);

  return (
    <div
      className="bg-white flex flex-col overflow-hidden animate-in fade-in duration-150"
      style={{ position: "fixed", inset: 0, zIndex: 9999, width: "100vw", height: "100vh" }}
    >
      {/* Top Header Bar */}
      <header className="shrink-0 flex items-center justify-between px-4 sm:px-8 py-3.5 sm:py-4 border-b border-stone-200 bg-white/95 backdrop-blur-xs">
        <div className="flex items-center gap-3 min-w-0">
          <button
            type="button"
            onClick={onClose}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-stone-700 hover:bg-stone-100 border border-stone-300 transition-colors shrink-0"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back</span>
          </button>
          <div className="min-w-0">
            <h2 className="text-sm sm:text-base font-bold text-stone-900 leading-tight truncate">
              {docMeta.title}
            </h2>
            <p className="text-[11px] sm:text-xs text-stone-500 truncate hidden sm:block">
              {docMeta.subtitle}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <span className="inline-flex items-center gap-1 text-[11px] sm:text-xs font-semibold text-emerald-800 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
            <span className="hidden sm:inline">Signed &</span> Active
          </span>
          <button
            type="button"
            onClick={onClose}
            className="p-2 text-stone-400 hover:text-stone-700 rounded-xl hover:bg-stone-100 transition-colors"
            aria-label="Close modal"
          >
            <X size={20} />
          </button>
        </div>
      </header>

      {/* Full Screen Scrollable Document Content */}
      <main className="flex-1 overflow-y-auto px-4 sm:px-8 py-6 sm:py-10">
        <div className="max-w-3xl mx-auto space-y-8 text-stone-800">
          {/* Document Title Header */}
          <div className="border-b border-stone-200 pb-5">
            <h1 className="text-xl sm:text-3xl font-bold text-stone-900 tracking-tight">
              {docMeta.title}
            </h1>
            <p className="text-xs sm:text-sm text-stone-500 mt-1.5 leading-relaxed">
              {docMeta.subtitle}
            </p>
          </div>

          {/* Section Clauses */}
          <div className="space-y-8">
            {docMeta.sections.map((section) => (
              <section key={section.id} id={section.id} className="space-y-3">
                <h3 className="text-base sm:text-lg font-bold text-stone-900 pb-1.5 border-b border-stone-100">
                  {section.title}
                </h3>
                <div className="text-xs sm:text-sm text-stone-600 leading-relaxed space-y-3">
                  {section.content}
                </div>
              </section>
            ))}
          </div>

          {/* Bottom Close Action */}
          <div className="pt-8 pb-12 border-t border-stone-200 flex justify-center">
            <button
              type="button"
              onClick={onClose}
              className="px-8 py-3 rounded-xl text-sm font-semibold bg-stone-900 text-white hover:bg-stone-800 transition-colors shadow-xs"
            >
              Close Document
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default TermsAndConditionsModal;
